//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLiberationFront.MongoDB.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProviderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProviderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalLiberationFront.MongoDB.Web.Resources.ProviderResources", typeof(ProviderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name cannot contain the &apos;{0}&apos; character..
        /// </summary>
        internal static string ApplicationNameCannotContainCharacter {
            get {
                return ResourceManager.GetString("ApplicationNameCannotContainCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decode passwords with &apos;{0}&apos; password format..
        /// </summary>
        internal static string CannotDecodePassword {
            get {
                return ResourceManager.GetString("CannotDecodePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete populated roles..
        /// </summary>
        internal static string CannotDeletePopulatedRoles {
            get {
                return ResourceManager.GetString("CannotDeletePopulatedRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve passwords when &apos;{0}&apos; is the password format..
        /// </summary>
        internal static string CannotRetrievePasswords {
            get {
                return ResourceManager.GetString("CannotRetrievePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add users to roles..
        /// </summary>
        internal static string CouldNotAddUsersToRoles {
            get {
                return ResourceManager.GetString("CouldNotAddUsersToRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change password..
        /// </summary>
        internal static string CouldNotChangePassword {
            get {
                return ResourceManager.GetString("CouldNotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change password question and answer..
        /// </summary>
        internal static string CouldNotChangePasswordQuestionAndAnswer {
            get {
                return ResourceManager.GetString("CouldNotChangePasswordQuestionAndAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not count profiles..
        /// </summary>
        internal static string CouldNotCountProfiles {
            get {
                return ResourceManager.GetString("CouldNotCountProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not count users..
        /// </summary>
        internal static string CouldNotCountUsers {
            get {
                return ResourceManager.GetString("CouldNotCountUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not count users in roles..
        /// </summary>
        internal static string CouldNotCountUsersInRoles {
            get {
                return ResourceManager.GetString("CouldNotCountUsersInRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create role..
        /// </summary>
        internal static string CouldNotCreateRole {
            get {
                return ResourceManager.GetString("CouldNotCreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create session..
        /// </summary>
        internal static string CouldNotCreateSession {
            get {
                return ResourceManager.GetString("CouldNotCreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create user..
        /// </summary>
        internal static string CouldNotCreateUser {
            get {
                return ResourceManager.GetString("CouldNotCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find user..
        /// </summary>
        internal static string CouldNotFindUser {
            get {
                return ResourceManager.GetString("CouldNotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove profiles..
        /// </summary>
        internal static string CouldNotRemoveProfiles {
            get {
                return ResourceManager.GetString("CouldNotRemoveProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete role..
        /// </summary>
        internal static string CouldNotRemoveRole {
            get {
                return ResourceManager.GetString("CouldNotRemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove session..
        /// </summary>
        internal static string CouldNotRemoveSession {
            get {
                return ResourceManager.GetString("CouldNotRemoveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove user..
        /// </summary>
        internal static string CouldNotRemoveUser {
            get {
                return ResourceManager.GetString("CouldNotRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove users from roles..
        /// </summary>
        internal static string CouldNotRemoveUsersFromRoles {
            get {
                return ResourceManager.GetString("CouldNotRemoveUsersFromRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reset password..
        /// </summary>
        internal static string CouldNotResetPassword {
            get {
                return ResourceManager.GetString("CouldNotResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve profile..
        /// </summary>
        internal static string CouldNotRetrieveProfile {
            get {
                return ResourceManager.GetString("CouldNotRetrieveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve role..
        /// </summary>
        internal static string CouldNotRetrieveRole {
            get {
                return ResourceManager.GetString("CouldNotRetrieveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve roles..
        /// </summary>
        internal static string CouldNotRetrieveRoles {
            get {
                return ResourceManager.GetString("CouldNotRetrieveRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve session..
        /// </summary>
        internal static string CouldNotRetrieveSession {
            get {
                return ResourceManager.GetString("CouldNotRetrieveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve user..
        /// </summary>
        internal static string CouldNotRetrieveUser {
            get {
                return ResourceManager.GetString("CouldNotRetrieveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve users in roles..
        /// </summary>
        internal static string CouldNotRetrieveUsersInRoles {
            get {
                return ResourceManager.GetString("CouldNotRetrieveUsersInRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update profile..
        /// </summary>
        internal static string CouldNotUpdateProfile {
            get {
                return ResourceManager.GetString("CouldNotUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update session..
        /// </summary>
        internal static string CouldNotUpdateSession {
            get {
                return ResourceManager.GetString("CouldNotUpdateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update user..
        /// </summary>
        internal static string CouldNotUpdateUser {
            get {
                return ResourceManager.GetString("CouldNotUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field to match must not be white-space..
        /// </summary>
        internal static string FieldToMatchMustNotBeWhiteSpace {
            get {
                return ResourceManager.GetString("FieldToMatchMustNotBeWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal session key name.  Session key names must not contain &apos;.&apos; or start with &apos;$&apos;..
        /// </summary>
        internal static string IllegalSessionKeyName {
            get {
                return ResourceManager.GetString("IllegalSessionKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password answer..
        /// </summary>
        internal static string IncorrectPasswordAnswer {
            get {
                return ResourceManager.GetString("IncorrectPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock id must be an ObjectId..
        /// </summary>
        internal static string LockIdMustBeAnObjectId {
            get {
                return ResourceManager.GetString("LockIdMustBeAnObjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum required password length must be &gt; 0..
        /// </summary>
        internal static string MinimumPasswordLengthMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MinimumPasswordLengthMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password answer cannot be null or white space..
        /// </summary>
        internal static string NewPasswordAnswerCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("NewPasswordAnswerCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be null or white space..
        /// </summary>
        internal static string NewPasswordCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("NewPasswordCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password question cannot be null or white space..
        /// </summary>
        internal static string NewPasswordQuestionCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("NewPasswordQuestionCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password cannot be null or white space..
        /// </summary>
        internal static string OldPasswordCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("OldPasswordCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index must be &gt;= 0..
        /// </summary>
        internal static string PageIndexMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("PageIndexMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be &gt;= 0..
        /// </summary>
        internal static string PageSizeMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("PageSizeMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password answer cannot be null or white space..
        /// </summary>
        internal static string PasswordAnswerCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("PasswordAnswerCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be null or white space..
        /// </summary>
        internal static string PasswordCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("PasswordCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change cancelled..
        /// </summary>
        internal static string PasswordChangeCancelled {
            get {
                return ResourceManager.GetString("PasswordChangeCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password format &apos;{0}&apos; not supported..
        /// </summary>
        internal static string PasswordFormatNotSupported {
            get {
                return ResourceManager.GetString("PasswordFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset is disabled..
        /// </summary>
        internal static string PasswordResetIsDisabled {
            get {
                return ResourceManager.GetString("PasswordResetIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password retrieval is disabled..
        /// </summary>
        internal static string PasswordRetrievalIsDisabled {
            get {
                return ResourceManager.GetString("PasswordRetrievalIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the provider has a length of zero..
        /// </summary>
        internal static string ProviderNameHasZeroLength {
            get {
                return ResourceManager.GetString("ProviderNameHasZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role does not exist..
        /// </summary>
        internal static string RoleDoesNotExist {
            get {
                return ResourceManager.GetString("RoleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name already exists..
        /// </summary>
        internal static string RoleNameAlreadyExists {
            get {
                return ResourceManager.GetString("RoleNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name cannot be null or white space..
        /// </summary>
        internal static string RoleNameCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("RoleNameCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name cannot contain the &apos;{0}&apos; character..
        /// </summary>
        internal static string RoleNameCannotContainCharacter {
            get {
                return ResourceManager.GetString("RoleNameCannotContainCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip must be &gt;= 0..
        /// </summary>
        internal static string SkipMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("SkipMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take must be &gt;= 0..
        /// </summary>
        internal static string TakeMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("TakeMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has a duplicate e-mail address..
        /// </summary>
        internal static string UserHasADuplicateEmailAddress {
            get {
                return ResourceManager.GetString("UserHasADuplicateEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has a duplicate name..
        /// </summary>
        internal static string UserHasADuplicateName {
            get {
                return ResourceManager.GetString("UserHasADuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already in role..
        /// </summary>
        internal static string UserIsAlreadyInRole {
            get {
                return ResourceManager.GetString("UserIsAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out..
        /// </summary>
        internal static string UserIsLockedOut {
            get {
                return ResourceManager.GetString("UserIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in role..
        /// </summary>
        internal static string UserIsNotInRole {
            get {
                return ResourceManager.GetString("UserIsNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be null or white space..
        /// </summary>
        internal static string UserNameCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("UserNameCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
    }
}
