//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalLiberationFront.Mongo.Web.Security.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProviderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProviderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalLiberationFront.Mongo.Web.Security.Resources.ProviderResources", typeof(ProviderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decode passwords with &apos;{0}&apos; password format..
        /// </summary>
        internal static string Membership_CannotDecodePassword {
            get {
                return ResourceManager.GetString("Membership_CannotDecodePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve passwords when &apos;{0}&apos; is the password format..
        /// </summary>
        internal static string Membership_CannotRetrievePasswords {
            get {
                return ResourceManager.GetString("Membership_CannotRetrievePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change password..
        /// </summary>
        internal static string Membership_CouldNotChangePassword {
            get {
                return ResourceManager.GetString("Membership_CouldNotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change password question and answer..
        /// </summary>
        internal static string Membership_CouldNotChangePasswordQuestionAndAnswer {
            get {
                return ResourceManager.GetString("Membership_CouldNotChangePasswordQuestionAndAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reset password..
        /// </summary>
        internal static string Membership_CouldNotResetPassword {
            get {
                return ResourceManager.GetString("Membership_CouldNotResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update user..
        /// </summary>
        internal static string Membership_CouldNotUpdateUser {
            get {
                return ResourceManager.GetString("Membership_CouldNotUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field to match must not be white-space..
        /// </summary>
        internal static string Membership_FieldToMatchMustNotBeWhiteSpace {
            get {
                return ResourceManager.GetString("Membership_FieldToMatchMustNotBeWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password answer..
        /// </summary>
        internal static string Membership_IncorrectPasswordAnswer {
            get {
                return ResourceManager.GetString("Membership_IncorrectPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password answer cannot be null or white space..
        /// </summary>
        internal static string Membership_NewPasswordAnswerCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Membership_NewPasswordAnswerCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be null or white space..
        /// </summary>
        internal static string Membership_NewPasswordCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Membership_NewPasswordCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password question cannot be null or white space..
        /// </summary>
        internal static string Membership_NewPasswordQuestionCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Membership_NewPasswordQuestionCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password cannot be null or white space..
        /// </summary>
        internal static string Membership_OldPasswordCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Membership_OldPasswordCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index must be &gt;= 0..
        /// </summary>
        internal static string Membership_PageIndexMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Membership_PageIndexMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be &gt;= 0..
        /// </summary>
        internal static string Membership_PageSizeMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Membership_PageSizeMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password answer cannot be null or white space..
        /// </summary>
        internal static string Membership_PasswordAnswerCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Membership_PasswordAnswerCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be null or white space..
        /// </summary>
        internal static string Membership_PasswordCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Membership_PasswordCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password format &apos;{0}&apos; not supported..
        /// </summary>
        internal static string Membership_PasswordFormatNotSupported {
            get {
                return ResourceManager.GetString("Membership_PasswordFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt is made to call Initialize on a provider after the provider has already been initialized..
        /// </summary>
        internal static string Membership_ProviderAlreadyInitialized {
            get {
                return ResourceManager.GetString("Membership_ProviderAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the provider has a length of zero..
        /// </summary>
        internal static string Membership_ProviderNameHasZeroLength {
            get {
                return ResourceManager.GetString("Membership_ProviderNameHasZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip must be &gt;= 0..
        /// </summary>
        internal static string Membership_SkipMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Membership_SkipMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take must be &gt;= 0..
        /// </summary>
        internal static string Membership_TakeMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Membership_TakeMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        internal static string Membership_UserDoesNotExist {
            get {
                return ResourceManager.GetString("Membership_UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has a duplicate e-mail address..
        /// </summary>
        internal static string Membership_UserHasADuplicateEmailAddress {
            get {
                return ResourceManager.GetString("Membership_UserHasADuplicateEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be null or white space..
        /// </summary>
        internal static string Membership_UserNameCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Membership_UserNameCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
    }
}
